version: "3.8"
services:
  zabbix-mysql:
    image: mysql:5.7.31
    container_name: zabbix-mysql
    #network_mode: host
    command:
      - mysqld
      - --character-set-server=utf8mb4
      - --default-authentication-plugin=mysql_native_password
      #- --bind-address = 127.0.0.1
    ports:
      - "3306:3306"
    volumes:
      - ./zabbix/var/lib/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=pwd
      - MYSQL_DATABASE=zabbix2
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=123
    restart: always
    networks:
      zbx_net_backend:
       aliases:
        - mysql-server

        
  zabbix-server:
    image: zabbix/zabbix-server-mysql
    volumes:
      - ./zabbix/alertscripts:/usr/lib/zabbix/alertscripts
    restart: always
    #network_mode: host
    links:
      - zabbix-mysql
    ports:
      - "10052:10052"
    environment:
      #- DB_SERVER_HOST=host.docker.internal
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=123
      - MYSQL_DATABASE=zabbix2
      - ZBX_HISTORYSTORAGETYPES=log,text
      - ZBX_DEBUGLEVEL=3
      - ZBX_HOUSEKEEPINGFREQUENCY=1
      - ZBX_MAXHOUSEKEEPERDELETE=5000
    depends_on:
      - zabbix-mysql
    networks:
      zbx_net_backend:
        aliases:
          - zabbix-server
          - zabbix-server-mysql
          - zabbix-server-alpine-mysql
          - zabbix-server-mysql-alpine
      zbx_net_frontend:
    sysctls:
        - net.ipv4.ip_local_port_range=1024 65000
        - net.ipv4.conf.all.accept_redirects=0
        - net.ipv4.conf.all.secure_redirects=0
        - net.ipv4.conf.all.send_redirects=0
 
  zabbix-web-apache:
    image: zabbix/zabbix-web-apache-mysql
    container_name: zabbix-web
    #network_mode: host
    restart: always
    environment:
      #- DB_SERVER_HOST=host.docker.internal
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=123
      - MYSQL_DATABASE=zabbix2
      - ZBX_SERVER_HOST=zabbix-server
      - ZBX_POSTMAXSIZE=16M
      - PHP_TZ=Europe/Riga
      - ZBX_MAXEXECUTIONTIME=500
    depends_on:
      - zabbix-mysql
      - zabbix-server
    networks:
      zbx_net_backend:
        aliases:
          - zabbix-web-apache-mysql
          - zabbix-web-apache-alpine-mysql
          - zabbix-web-apache-mysql-alpine
      zbx_net_frontend:
    sysctls:
        - net.core.somaxconn=65535
    ports:  
      - "8085:7080"
      - "1443:8443"
  
  zabbix-agent:
    privileged: true
    image: zabbix/zabbix-agent
    ports:
      - "10050:10050"
    network_mode: host
    restart: unless-stopped
    environment:
      - ZBX_SERVER_HOST=zabbix-server

networks:
  zbx_net_frontend:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 172.16.230.0/24
  zbx_net_backend:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    internal: true
    ipam:
      driver: default
      config:
      - subnet: 172.16.231.0/24
  elastic:
  logstach:
    image: logstash:3.0.0
  kibana:
